id: A7A0B1191
title: Prayer for the Long Life of Chökyi Nyima Rinpoche
type: translation
pechas:
- I9D909A91
- I06D6E648
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:48:10.939284
  last_modified_at: 2023-01-04 11:48:10.939295
  collections:
  - Dudjom Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  I9D909A91/92DB: '1675'
  I06D6E648/9475: '1675'
